// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1ItuGGithAx_Guwhz5NZC2kZ8Ns1aspE',
    appId: '1:194333651657:web:20db64b6e4cfac7515d318',
    messagingSenderId: '194333651657',
    projectId: 'to-do-app-c13ed',
    authDomain: 'to-do-app-c13ed.firebaseapp.com',
    storageBucket: 'to-do-app-c13ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxQaKLe9osz3Rf7Rl9GyJJ5yRvM2CHFIg',
    appId: '1:194333651657:android:0ecca8a866402b5115d318',
    messagingSenderId: '194333651657',
    projectId: 'to-do-app-c13ed',
    storageBucket: 'to-do-app-c13ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC45uNUcIrZl-dw74Vr-YHOraeS61J6XMI',
    appId: '1:194333651657:ios:7564db597e93636915d318',
    messagingSenderId: '194333651657',
    projectId: 'to-do-app-c13ed',
    storageBucket: 'to-do-app-c13ed.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC45uNUcIrZl-dw74Vr-YHOraeS61J6XMI',
    appId: '1:194333651657:ios:779477b0213f933a15d318',
    messagingSenderId: '194333651657',
    projectId: 'to-do-app-c13ed',
    storageBucket: 'to-do-app-c13ed.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
